version: "3.7"
services:
  teamspeak:
    image: qmcgaw/teamspeak3-alpine
    container_name: teamspeak
    volumes:
      - ./data:/teamspeak/data
      - ./logs:/teamspeak/logs
    network_mode: bridge
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
    environment:
      #- TS3SERVER_LICENSE=accept
    restart: always
